### PR TITLE
Update config and deps; release v0.2.0

### PR DESCRIPTION
**Pull request by d00rman**
This patch brings mediawiki-node-services up to date with the latest RESTBase and service-runner developments.

### CODE REVIEW

**Comment by d00rman** [comment]
cc @wikimedia/services

**Comment by d00rman** [comment]
Depends on [service-runner#123](https://github.com/wikimedia/service-runner/pull/123)

**Comment by d00rman** [comment]
Ready to go now

**Comment by d00rman** [comment]
@wikimedia/services ping!

**Comment by gwicke** [comment]
Thanks for updating this, @d00rman!

**Pull request merged**
