### PR TITLE
Update dependencies and config; release v0.2.1

### PR DESCRIPTION
**Pull request by d00rman**

### CODE REVIEW

**Comment by d00rman** [comment]
cc @wikimedia/services

**Comment by Pchelolo** [comment]
Hm.. I guess we need to add change-prop here as well. It's useless without it..

**Comment by d00rman** [comment]
I wouldn't really put it that it's useless without it, but I agree that we need to add CP as well as other services, but we need to add the dep to Kafka for that first, so this PR shouldn't contain it.

**Comment by Pchelolo** [comment]
Ye, agreed. +1 to the PR

**Comment by d00rman** [comment]
Tagged and pushed as [v0.2.1](https://hub.docker.com/r/wikimedia/mediawiki-node-services/tags/)

**Pull request merged**
